### ISSUE TITLE
global_ignore_columns doesn't work 

### ISSUE THREAD

**Issue by mitalcoi** [simplethings/EntityAuditBundle#258]
EntityAuditBundle doesn't ignore column, and track any update of global_ignore_columns

```
"simplethings/entity-audit-bundle": "^1.0"
"symfony/symfony": "2.7.*",
"doctrine/orm": "^2.4.8, <2.5"
```

My config:
```
simple_things_entity_audit:
    audited_entities:
        - AppBundle\Entity\Order
    global_ignore_columns:
        - createdAt
        - status
```
My Entity:

```
/**
 * @ORM\Table(name="mpay_order")
 */
class Order
{
    /**
     * @ORM\Column(type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    protected $id;
    /**
     * @ORM\Column(type="integer")
     */
    protected $status;
    /**
     * @ORM\Column(type="datetime")
     */
    protected $createdAt;
```
