### ISSUE TITLE
Invalid configuration

### ISSUE THREAD

**Issue by gundamkid** [simplethings/EntityAuditBundle#294]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | yes/no
| BC Break report? | yes/no

I tried to ignore some columns follow your documentation but i get this error: 
````
[Symfony\Component\Config\Definition\Exception\InvalidConfigurationException]   
  Unrecognized option "global_ignore_columns" under "simple_things_entity_audit"
````

this is my configuraton:
````
simple_things_entity_audit:
    global_ignore_columns:
        - created_at
        - modified_at
    service:
        username_callable: i_care_core.audit_user_provider.callable
    audited_entities:
        - MyBundle\Entity\Member
````

What wrong with me? 

Thank you!
